services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./src/:/app

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./src/:/app

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - exp-volume:/var/lib/mysql

  # mailhog追記 参考:https://zenn.dev/naoki0722/articles/5b8bd8fdc22bb8 24/2/7 12:20
  mail:
    image: mailhog/mailhog
    container_name: exp_mailhog
    ports:
      - "8025:8025"
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp

volumes:
  exp-volume:
  maildir: {}