name: Laravel CI

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  laravel-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2', '8.3' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, pdo_sqlite, dom, fileinfo
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: src/vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('src/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-composer-
            ${{ runner.os }}-php-

      - name: Install Composer dependencies
        working-directory: src
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Copy .env
        working-directory: src
        run: cp .env.example .env

      - name: Generate app key
        working-directory: src
        run: php artisan key:generate

      - name: Check artisan works
        working-directory: src
        run: php artisan about

      - name: Prepare SQLite database file
        working-directory: src
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Create .env.testing
        working-directory: src
        run: |
          cat > .env.testing << 'EOF'
          APP_ENV=testing
          CACHE_DRIVER=array
          SESSION_DRIVER=array
          QUEUE_CONNECTION=sync
          DB_CONNECTION=sqlite
          DB_DATABASE=database/database.sqlite
          EOF

      - name: Set testing APP_KEY
        working-directory: src
        shell: bash
        run: |
          KEY=$(php artisan key:generate --show)
          printf "\nAPP_KEY=%s\n" "$KEY" >> .env.testing

      - name: Clear config cache
        working-directory: src
        run: php artisan config:clear

      - name: Migrate
        working-directory: src
        run: php artisan migrate --env=testing --force

      - name: Run tests
        working-directory: src
        run: php artisan test