name: Laravel CI Level 0

on:
  pull_request:
    branches: [ develop ]   # feature → develop のPRで発火
  push:
    branches: [ develop ]   # developへの直接pushでも発火

jobs:
  laravel-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'   # プロジェクトのバージョンに合わせる
          extensions: mbstring, intl, pdo_sqlite, dom, fileinfo
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Check artisan works
        run: php artisan about